
[colors]
draw_bold_text_with_bright_colors = true

[font]
# normal = {family="Cascadia Code", style="Regular"} -- WHAT I'M CURRENTLY USING

# normal = {family="SourceCodePro", style="Regular"}
# bold = {family="Hack Nerd Font", style = "bold"}

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleFullScreen"
key = "F11"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
dynamic_title = true
decorations = "None"
#opacity = 0.92
opacity = 1
startup_mode = "Maximized"
title = "eroblaze"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[general]
live_config_reload = true
import = ["/home/eroblaze/.config/alacritty/tokyonight_night.toml"]

[terminal.shell]
#args = ["-l", "-c", "tmux attach || tmux"]
program = "/usr/bin/fish"
