[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[font]
# normal = {family="CaskaydiaCove Nerd Font Mono", style="Regular"} 
normal = {family="CaskaydiaMono Nerd Font", style="Regular"} 
bold = {family="CaskaydiaMono Nerd Font", style="Bold"} 
italic = {family="CaskaydiaMono Nerd Font", style="Italic"} 
size = 11


[keyboard]
bindings = [
  { key = "V", mods = "Control|Shift", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "Key0", mods = "Control", action = "ResetFontSize" },
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
  { key = "F11", action = "ToggleFullScreen" },
  { key = "Return", mods = "Shift|Control", action = "SpawnNewInstance" },
]

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
dynamic_title = true
dynamic_padding = true
opacity = 0.98
startup_mode = "Maximized"
title = "eroblaze"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[general]
live_config_reload = true
import = ["~/.config/omarchy/current/theme/alacritty.toml"]
# import = ["/home/eroblaze/.config/alacritty/tokyonight_night.toml"]

[terminal.shell]
#args = ["-l", "-c", "tmux attach || tmux"]
program = "/usr/bin/fish"
